/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Car;
import org.springframework.http.HttpEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.HashMap;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-25T10:59:21.087Z")

@Api(value = "car", description = "the car API")
public interface CarApi {

    @ApiOperation(value = "Get cars", nickname = "getCars", notes = "Return test values for cars", response = Car.class, responseContainer = "List", tags={ "car", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Car.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Invalid status value") })
    @CrossOrigin(origins = "*")
    @RequestMapping(value = "/cars",
            produces = { "application/json" },
            consumes = "application/json",
            method = RequestMethod.POST)
    ResponseEntity<List<Car>> getCars(HttpServletRequest request,
                                          HttpServletResponse response, @RequestBody HttpEntity<String> httpEntity);

    @CrossOrigin(origins = "*")
    @RequestMapping(value = "/numberofcars",
            consumes = "application/json",
            method = RequestMethod.POST)
    ResponseEntity<Integer> getNumberOfCars(HttpServletRequest request,
                                                HttpServletResponse response, @RequestBody HttpEntity<String> httpEntity);

    @CrossOrigin(origins = "*")
    @RequestMapping(value = "/numberofrequirement",
            consumes = "application/json",
            produces = "application/json",
            method = RequestMethod.POST)
    ResponseEntity getNumberOfRequirements(HttpServletRequest request,
                                            HttpServletResponse response, @RequestBody HttpEntity<String> httpEntity);
}
