version: '3'
volumes:
  mysql-data:
services:
  back_end:
    build: .
    image: mycarbackend
    links:
      - db:mariadb
    ports: 
      - "8001:8001"
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=@SQLpassword123
      - MYSQL_DATABASE=mycar
      - MYSQL_USER=josquin
      - MYSQL_PASSWORD=@SQLpassword123
    volumes:
      - mysql-data:/var/lib/mysql
